"""
=============================================================================
  IMAGE CLUSTERER — K-Means grouping using deep feature extraction
  Dataset: Microsoft Cats vs Dogs (Kaggle)
  Author:  Generated by Claude
=============================================================================

Pipeline overview:
  1. Scan project folder for images
  2. Extract deep feature vectors via MobileNetV2 (pretrained on ImageNet)
  3. Reduce dimensionality with PCA  (keeps 95 % of variance)
  4. Cluster with K-Means
  5. Copy images into cluster subfolders inside the project directory
"""

import os
import sys
import time
import shutil
import logging
import argparse
from pathlib import Path
from datetime import datetime

import numpy as np
from PIL import Image

# ── Lazy TF import to keep startup messages tidy ──────────────────────────────
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"  # silence TF C++ logs
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.models import Model

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler


# =============================================================================
#  LOGGING SETUP
# =============================================================================

def setup_logger(log_dir: Path) -> logging.Logger:
    """Configure a logger that writes to both console and a log file."""
    log_dir.mkdir(parents=True, exist_ok=True)
    log_file = log_dir / f"run_{datetime.now():%Y%m%d_%H%M%S}.log"

    fmt = "[%(asctime)s]  %(levelname)-8s  %(message)s"
    datefmt = "%H:%M:%S"

    logging.basicConfig(
        level=logging.INFO,
        format=fmt,
        datefmt=datefmt,
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(log_file, encoding="utf-8"),
        ],
    )
    logger = logging.getLogger("ImageClusterer")
    logger.info(f"Log file: {log_file}")
    return logger


# =============================================================================
#  STEP 1 — SCAN FOR IMAGES
# =============================================================================

SUPPORTED_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp"}


def collect_image_paths(root: Path, logger: logging.Logger) -> list[Path]:
    """
    Recursively scan *root* for image files.
    Skips any subfolder that looks like a cluster output (starts with 'cluster_').
    """
    logger.info("=" * 60)
    logger.info("STEP 1 — Scanning for images")
    logger.info(f"  Root directory : {root}")

    paths = []
    skipped_dirs = 0

    for dirpath, dirnames, filenames in os.walk(root):
        # Skip previously created cluster folders so re-runs don't re-cluster
        dirnames[:] = [
            d for d in dirnames if not d.lower().startswith("cluster_")
        ]

        for fname in filenames:
            if Path(fname).suffix.lower() in SUPPORTED_EXTS:
                paths.append(Path(dirpath) / fname)

    logger.info(f"  Found {len(paths)} image(s)")
    if len(paths) == 0:
        logger.error("  No images found! Check that the dataset is inside the project folder.")
        sys.exit(1)

    return paths


# =============================================================================
#  STEP 2 — FEATURE EXTRACTION
# =============================================================================

IMG_SIZE = (224, 224)  # MobileNetV2 native input size


def build_feature_extractor(logger: logging.Logger) -> Model:
    """
    Load MobileNetV2 pretrained on ImageNet and strip the classification head.
    The output is the 1280-d global-average-pool layer → rich visual features.
    """
    logger.info("=" * 60)
    logger.info("STEP 2 — Building feature extractor (MobileNetV2)")

    base = MobileNetV2(weights="imagenet", include_top=False, pooling="avg",
                       input_shape=(*IMG_SIZE, 3))
    base.trainable = False  # freeze weights — we only need forward pass
    model = Model(inputs=base.input, outputs=base.output)

    logger.info(f"  Model loaded  : MobileNetV2 (ImageNet weights)")
    logger.info(f"  Feature dim   : {model.output_shape[-1]}")
    return model


def load_and_preprocess(path: Path) -> np.ndarray | None:
    """
    Open one image, resize to 224×224, convert to RGB, apply MobileNetV2
    preprocessing (scales pixels to [-1, 1]).
    Returns None if the file cannot be read.
    """
    try:
        img = Image.open(path).convert("RGB").resize(IMG_SIZE)
        arr = np.array(img, dtype=np.float32)
        return preprocess_input(arr)  # in-place scale to [-1, 1]
    except Exception as exc:
        return None


def extract_features(paths: list[Path], model: Model,
                     batch_size: int, logger: logging.Logger) -> tuple[np.ndarray, list[Path]]:
    """
    Run all images through the feature extractor in mini-batches.
    Returns the feature matrix and the list of paths that succeeded.
    """
    logger.info("=" * 60)
    logger.info("STEP 2 — Extracting features from images")
    logger.info(f"  Batch size  : {batch_size}")
    logger.info(f"  Total images: {len(paths)}")

    features = []
    valid_paths = []
    failed = 0
    total = len(paths)

    t0 = time.time()
    for batch_start in range(0, total, batch_size):
        batch_paths = paths[batch_start: batch_start + batch_size]
        batch_imgs = []
        batch_valid = []

        for p in batch_paths:
            arr = load_and_preprocess(p)
            if arr is None:
                logger.warning(f"  Skipping unreadable file: {p.name}")
                failed += 1
            else:
                batch_imgs.append(arr)
                batch_valid.append(p)

        if batch_imgs:
            batch_tensor = np.stack(batch_imgs, axis=0)
            batch_feats = model.predict(batch_tensor, verbose=0)
            features.append(batch_feats)
            valid_paths.extend(batch_valid)

        done = min(batch_start + batch_size, total)
        elapsed = time.time() - t0
        pct = done / total * 100
        logger.info(f"  Progress: {done:>5}/{total}  ({pct:5.1f}%)  "
                    f"elapsed {elapsed:.1f}s")

    feature_matrix = np.vstack(features)
    logger.info(f"  Feature extraction complete.")
    logger.info(f"  Successful : {len(valid_paths)}  |  Failed: {failed}")
    logger.info(f"  Feature matrix shape: {feature_matrix.shape}")
    return feature_matrix, valid_paths


# =============================================================================
#  STEP 3 — DIMENSIONALITY REDUCTION (PCA)
# =============================================================================

def reduce_with_pca(features: np.ndarray, variance_threshold: float,
                    logger: logging.Logger) -> np.ndarray:
    """
    Standardise features then apply PCA, retaining *variance_threshold*
    fraction of total variance (default 0.95).
    """
    logger.info("=" * 60)
    logger.info("STEP 3 — Dimensionality reduction with PCA")
    logger.info(f"  Original dimensions : {features.shape[1]}")
    logger.info(f"  Target variance kept: {variance_threshold * 100:.0f}%")

    # Standardise so each feature has zero mean and unit variance
    scaler = StandardScaler()
    features_scaled = scaler.fit_transform(features)

    pca = PCA(n_components=variance_threshold, svd_solver="full", random_state=42)
    reduced = pca.fit_transform(features_scaled)

    logger.info(f"  Reduced dimensions  : {reduced.shape[1]}")
    logger.info(f"  Actual variance kept: {pca.explained_variance_ratio_.sum() * 100:.2f}%")
    return reduced


# =============================================================================
#  STEP 4 — K-MEANS CLUSTERING
# =============================================================================

def cluster_features(features: np.ndarray, k: int,
                     logger: logging.Logger) -> np.ndarray:
    """
    Fit K-Means on the (PCA-reduced) feature matrix and return cluster labels.
    """
    logger.info("=" * 60)
    logger.info("STEP 4 — K-Means clustering")
    logger.info(f"  Number of clusters (k): {k}")
    logger.info(f"  Samples to cluster    : {features.shape[0]}")

    kmeans = KMeans(
        n_clusters=k,
        init="k-means++",   # smarter initialisation — faster convergence
        n_init=10,           # run 10 times, pick best inertia
        max_iter=300,
        random_state=42,
        verbose=0,
    )
    t0 = time.time()
    labels = kmeans.fit_predict(features)
    elapsed = time.time() - t0

    logger.info(f"  Clustering done in {elapsed:.2f}s")
    logger.info(f"  Inertia (lower = tighter clusters): {kmeans.inertia_:.2f}")

    # Print per-cluster counts
    for c in range(k):
        count = int((labels == c).sum())
        bar = "█" * (count * 30 // len(labels))
        logger.info(f"    Cluster {c:>2}: {count:>5} images  {bar}")

    return labels


# =============================================================================
#  STEP 5 — COPY FILES INTO CLUSTER SUBFOLDERS
# =============================================================================

def copy_to_clusters(paths: list[Path], labels: np.ndarray,
                     output_root: Path, logger: logging.Logger,
                     move: bool = False) -> None:
    """
    Create cluster_0/, cluster_1/, … inside *output_root* and
    copy (or move) each image into the appropriate subfolder.

    Parameters
    ----------
    move : if True, move files instead of copying (saves disk space).
    """
    logger.info("=" * 60)
    action = "Moving" if move else "Copying"
    logger.info(f"STEP 5 — {action} images into cluster subfolders")
    logger.info(f"  Output root: {output_root}")

    k = int(labels.max()) + 1

    # Create all cluster directories up-front
    cluster_dirs = {}
    for c in range(k):
        d = output_root / f"cluster_{c}"
        d.mkdir(parents=True, exist_ok=True)
        cluster_dirs[c] = d
        logger.info(f"  Created (or verified): {d}")

    # Transfer files
    total = len(paths)
    for idx, (src, label) in enumerate(zip(paths, labels)):
        dst = cluster_dirs[int(label)] / src.name

        # Handle filename collisions by appending an index
        if dst.exists():
            stem, suffix = src.stem, src.suffix
            dst = cluster_dirs[int(label)] / f"{stem}_{idx}{suffix}"

        try:
            if move:
                shutil.move(str(src), dst)
            else:
                shutil.copy2(src, dst)
        except Exception as exc:
            logger.warning(f"  Could not transfer {src.name}: {exc}")

        if (idx + 1) % 500 == 0 or (idx + 1) == total:
            logger.info(f"  Transferred {idx + 1}/{total} files…")

    logger.info(f"  Done! All images distributed into {k} cluster folders.")


# =============================================================================
#  MAIN
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Cluster images in a folder using K-Means + MobileNetV2 features."
    )
    parser.add_argument(
        "--images-dir", "-i",
        default="dataset",
        help="Subfolder (relative to project root) containing source images. "
             "Default: 'dataset'",
    )
    parser.add_argument(
        "--output-dir", "-o",
        default="clustered",
        help="Subfolder where cluster_N/ folders will be created. "
             "Default: 'clustered'",
    )
    parser.add_argument(
        "--k", "-k",
        type=int, default=2,
        help="Number of clusters. Default: 2 (cats / dogs)",
    )
    parser.add_argument(
        "--batch-size", "-b",
        type=int, default=32,
        help="Images per inference batch. Reduce if you run out of memory. Default: 32",
    )
    parser.add_argument(
        "--pca-variance", "-p",
        type=float, default=0.95,
        help="Fraction of variance to keep after PCA (0–1). Default: 0.95",
    )
    parser.add_argument(
        "--move",
        action="store_true",
        help="Move files instead of copying (saves disk space).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # ── Project root = directory of this script ───────────────────────────────
    project_root = Path(__file__).resolve().parent

    images_dir  = project_root / args.images_dir
    output_dir  = project_root / args.output_dir
    logs_dir    = project_root / "logs"

    logger = setup_logger(logs_dir)

    logger.info("=" * 60)
    logger.info("  IMAGE CLUSTERER  —  K-Means + MobileNetV2")
    logger.info("=" * 60)
    logger.info(f"  Project root : {project_root}")
    logger.info(f"  Images dir   : {images_dir}")
    logger.info(f"  Output dir   : {output_dir}")
    logger.info(f"  k (clusters) : {args.k}")
    logger.info(f"  Batch size   : {args.batch_size}")
    logger.info(f"  PCA variance : {args.pca_variance}")
    logger.info(f"  Move files   : {args.move}")
    logger.info("=" * 60)

    # Check that the images directory exists
    if not images_dir.exists():
        logger.error(f"Images directory not found: {images_dir}")
        logger.error("  → Create the folder and place your images there, then re-run.")
        sys.exit(1)

    # ── Pipeline ──────────────────────────────────────────────────────────────
    t_start = time.time()

    # 1. Collect paths
    all_paths = collect_image_paths(images_dir, logger)

    # 2. Build extractor & extract features
    extractor = build_feature_extractor(logger)
    features, valid_paths = extract_features(all_paths, extractor,
                                             args.batch_size, logger)

    # 3. PCA
    reduced = reduce_with_pca(features, args.pca_variance, logger)

    # 4. K-Means
    labels = cluster_features(reduced, args.k, logger)

    # 5. Copy/move files
    copy_to_clusters(valid_paths, labels, output_dir, logger, move=args.move)

    # ── Summary ───────────────────────────────────────────────────────────────
    total_time = time.time() - t_start
    logger.info("=" * 60)
    logger.info("  FINISHED SUCCESSFULLY")
    logger.info(f"  Total time   : {total_time:.1f}s  ({total_time/60:.1f} min)")
    logger.info(f"  Images sorted: {len(valid_paths)}")
    logger.info(f"  Output       : {output_dir}")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
